apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    name: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234
