Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.121.101"

  config.vm.provider "libvirt" do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
