services:
  gateway:
    build: ./gateway
    ports: 
        - "80:80"
    networks:
      - homeserver
    restart: unless-stopped
  free-stock-tickers:
    image: ghcr.io/le-quentin/free-stock-tickers:latest
    environment:
      APP_PORT: 3000
    networks:
      - homeserver
    restart: unless-stopped
  cocobot:
    image: ghcr.io/le-quentin/cocobot:nightly
    volumes:
      - /home/pi/cocobot:/app/data:ro
    environment:
      BOT_TOKEN: ${COCOBOT_TOKEN}
      LANGUAGE: fr
    restart: unless-stopped

networks:
  homeserver: {}
      
