- name: Setup piserv
  hosts: piserv
  become: yes
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
    portainer:
      host: localhost:9443
  vars_files:
    - ./passwords.yaml # Encrypted with GPG via git-crypt
  tasks:
   - name: Install git
     package:
       name: git
       state: present
   - include_tasks: "tasks/install-docker.yaml"
     tags: 
       - docker
   - include_tasks: "tasks/setup-portainer.yaml"
     tags:
       - portainer
   - include_tasks: "tasks/setup-services.yaml"
     tags:
       - services
