- name: Setup piserv
  hosts: piserv
  become: yes
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
    portainer:
      host: localhost:9443
  vars_files:
    - ./passwords.yaml # Encrypted with GPG via git-crypt
  tasks:
   - name: Install git
     package:
       name: git
       state: present
   - include_tasks: "tasks/setup-dnsmasq.yaml"
     tags:
       - dnsmasq
   - include_tasks: "tasks/setup-backups.yaml"
     tags:
       - backups
   - include_tasks: "tasks/install-docker.yaml"
     tags: 
       - docker-install
   - include_tasks: "tasks/setup-docker.yaml"
     tags:
       - docker
   - include_tasks: "tasks/setup-portainer.yaml"
     tags:
       - portainer
   - include_tasks: "tasks/setup-services.yaml"
     tags:
       - home-assistant
       - mautic
       - gateway
       - services
   - include_tasks: "tasks/setup-monitoring.yaml"
     tags:
       - monitoring
   - name: Run the node-exporter role
     tags:
       - monitoring
     include_role:
       name: prometheus.prometheus.node_exporter
