services:
  mautic:
    container_name: services_mautic
    image: mautic/mautic:5-apache
    restart: unless-stopped
    networks:
      - services-net
    depends_on:
      - mautic-database
    ports:
      - "4000:80"
    environment:
      MAUTIC_DB_HOST: mautic-database
      MAUTIC_DB_PORT: 3306
      MAUTIC_DB_DATABASE: ${MAUTIC_MYSQL_DATABASE}
      MAUTIC_DB_USER: ${MAUTIC_MYSQL_USER}
      MAUTIC_DB_PASSWORD: ${MAUTIC_MYSQL_PASSWORD}
      MAUTIC_RUN_CRON_JOBS: "true"
    volumes:
      - mautic-html:/var/www/html/mautic
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    healthcheck:
      test: curl http://localhost:4000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      mautic-database:
        condition: service_healthy

  mautic-database:
    container_name: services_mautic-database
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "4001:3306"
    networks:
      - services-net
    environment:
      MYSQL_USER: ${MAUTIC_MYSQL_USER}
      MYSQL_PASSWORD: ${MAUTIC_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MAUTIC_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MAUTIC_MYSQL_ROOT_PASSWORD}
    volumes:
      - mautic-database:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  mautic-mailhog:
    container_name: services_mautic-mailhog
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 4002:8025
    networks:
      - services-net

volumes:
  mautic-database:
  mautic-html:
networks:
  services-net:
    external: true

