- name: Check if docker is installed
  shell: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false
  failed_when: false
- include_tasks: "install-docker-{{ ansible_os_family }}.yaml"
  when: docker_installed.rc != 0
- name: Install docker python dependencies
  package:
    name: 
      - python3-docker
      - python3-compose
