 - include_tasks: "install-docker-{{ ansible_os_family }}.yaml"
 - name: Install docker python dependencies
   tags:
     - docker
   package:
     name: 
       - python3-docker
       - python3-compose
