- name: Create portainer container
  tags: 
    - portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce:2.19.4-alpine
    state: started
    recreate: yes
    restart_policy: unless-stopped
    published_ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ home_dir }}/portainer/data:/data"
    command: "--admin-password='{{ portainer.password }}'"
# - name: Setup portainer admin password 
#   tags: 
#     - portainer
#   uri:
#     url: "https://{{ portainer.host }}/api/users/admin/init"
#     method: POST
#     validate_certs: no
#     body_format: json
#     body:
#       username: "{{ portainer.username }}"
#       password: "{{ portainer.password }}"
