- name: Delete previous services files
  become: no
  tags:
    - always
  file:
    state: absent
    path: "{{ home_dir }}/services"
- name: Copy services files
  become: no
  tags:
    - always
  copy:
    src: "./services"
    dest: "{{ home_dir }}"
- name: Make sure the home-assistant volume exists
  community.docker.docker_volume:
    name: home-assistant-data
  tags:
    - home-assistant
    - services
- name: Interpert home-assistant docker compose template 
  tags:
    - home-assistant
    - services
  template:
    src: ./services/home-assistant/compose.yaml.j2
    dest: "{{ home_dir }}/services/home-assistant/compose.yaml"
- name: Run home-assistant in docker compose
  tags:
    - home-assistant
    - services
  community.docker.docker_compose_v2:
    project_src: "{{ home_dir }}/services/home-assistant"
    recreate: always # so that changes in config are applied
    build: always # rebuild home-assistant if changes are detected
- name: Run mautic services in docker compose
  tags:
    - mautic
    - services
  community.docker.docker_compose_v2:
    project_src: "{{ home_dir }}/services/mautic"
    recreate: always # so that changes in config are applied
    build: always # rebuild mautic if changes are detected
- name: Run gateway in docker compose
  tags:
    - gateway
    - services
  community.docker.docker_compose_v2:
    project_src: "{{ home_dir }}/services/gateway"
    recreate: always # so that changes in config are applied
    build: always # rebuild gateway if changes are detected
- name: Run other services in docker compose
  tags:
    - services
  community.docker.docker_compose_v2:
    project_src: "{{ home_dir }}/services"
    recreate: always # so that changes in config are applied
    build: always # rebuild gateway if changes are detected
