- name: Delete previous services files
  become: no
  tags:
    - services
  file:
    state: absent
    path: "{{ home_dir }}/services"
- name: Copy services files
  become: no
  tags:
    - services
  copy:
    src: "./services"
    dest: "{{ home_dir }}"
- name: Run services in docker compose
  tags:
    - services
  docker_compose:
    project_src: "{{ home_dir }}/services"
    recreate: always # so that changes in config are applied
    build: true # rebuild gateway if changes are detected
