- name: Delete previous monitoring services files
  become: no
  tags:
    - monitoring
  file:
    state: absent
    path: "{{ home_dir }}/monitoring"
- name: Copy monitoring services files
  become: no
  tags:
    - monitoring
  copy:
    src: "./monitoring"
    dest: "{{ home_dir }}"
- name: Run monitoring services in docker compose
  tags:
    - monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ home_dir }}/monitoring"
    recreate: always # so that changes in config are applied
    build: always
