- name: Copy services files
  become: no
  tags:
    - services
  copy:
    src: "./services"
    dest: "{{ home_dir }}"
- name: Run services in docker compose
  tags:
    - services
  docker_compose:
    project_src: "{{ home_dir }}/services"
