---
- name: Manually run local backups
  hosts: legacyhost
  vars:
    docker_volume_backup_root: "{{ ansible_files_root }}/docker-volume-backup"
    services: "{{ services-to-backup }}"
  tasks:
    - name: Run prometheus backup
      tags:
        - prometheus
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ docker_volume_backup_root }}"
        services:
          - backup-prometheus
        recreate: always # so that changes in config are applied
    - name: Run home-assistant backup
      tags:
        - home-assistant
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ docker_volume_backup_root }}"
        services:
          - backup-home-assistant
        recreate: always # so that changes in config are applied
    - name: Run zigbee2mqtt backup
      tags:
        - zigbee2mqtt
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ docker_volume_backup_root }}"
        services:
          - backup-zigbee2mqtt
        recreate: always # so that changes in config are applied
    - name: Run mosquitto backup
      tags:
        - mosquitto
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ docker_volume_backup_root }}"
        services:
          - backup-mosquitto
        recreate: always # so that changes in config are applied
