- name: Check If Docker Is Installed
  command: docker --version
  register: docker_installed
  ignore_errors: yes
  failed_when: false
  changed_when: false
- include_tasks: "install-docker-{{ ansible_os_family }}.yaml"
  when: docker_installed.rc != 0
- name: Install docker python dependencies
  become: yes
  package:
    name: 
      - python3-docker
      - python3-compose
