---
- name: Update and upgrade all packages to the latest version
  become: yes
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install required packages
  become: yes
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common

- name: Create directory for Docker's GPG key
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Print architecture variables
  ansible.builtin.debug:
    msg: "Architecture: {{ ansible_architecture_alt }}, Codename: {{ ansible_lsb.codename }}"

- name: Add Docker repository
  become: yes
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture_alt }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    filename: docker
    state: present

- name: Install Docker and related packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

# Uncomment to run docker without sudo
# - name: Add Docker group
#   ansible.builtin.group:
#     name: docker
#     state: present
#
# - name: Add user to Docker group
#   ansible.builtin.user:
#     name: "{{ ansible_user }}"
#     groups: docker
#     append: true

- name: Enable and start Docker services
  become: yes
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service
