- name: Set facts for databases
  ansible.builtin.set_fact:
    postgresql_databases: >-
      {{
        (postgresql_databases | default([])) + [{
          'name': item.name,
          'state': item.state | default('present')
        }]
      }}
  with_items: "{{ postgres_databases }}"
  no_log: "{{ postgres_no_log }}"
- name: Set facts for user access
  ansible.builtin.set_fact:
    postgresql_users: >-
      {{
        (postgresql_users | default([])) + [{
          'db': item.name,
          'name': item.user,
          'password': item.password,
          'encrypted': true,
          'priv': 'CONNECT/CREATE'
        }]
      }}
  with_items: "{{ present_databases }}"
  no_log: "{{ postgres_no_log }}"
