---
- name: Run backup
  block:
    - name: Scale down app before backup
      kubernetes.core.k8s_scale:
        kind: Deployment
        namespace: "{{ k3s_backups_namespace }}"
        replicas: 0
      when: k3s_backups_stop_app

    - name: Delete previous backup job (if it exists)
      kubernetes.core.k8s:
        state: absent
        kind: Job
        name: "manual-backup"
        namespace: "{{ k3s_backups_namespace }}"
        delete_options:
          propagationPolicy: Background

    - name: Render job YAML for debug
      debug:
        msg: "{{ lookup('template', 'backup-job.yaml.j2') }}"

    - name: Run backup job
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'backup-job.yaml.j2') }}"

    - name: Wait for backup job to complete
      kubernetes.core.k8s:
        state: present
        kind: Job
        namespace: "{{ k3s_backups_namespace }}"
        name: "manual-backup"
        wait: true
        wait_timeout: 600
        wait_condition:
          type: Complete
          status: "True"

  always:
    - name: Scale app back up
      kubernetes.core.k8s_scale:
        kind: Deployment
        namespace: "{{ k3s_backups_namespace }}"
        replicas: 1
      when: k3s_backups_stop_app
