- name: Remove rclone-config secret
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ k3s_backups_namespace }}"
    kind: Secret
    name: "{{ k3s_backups_rclone_secret_name }}"

- name: Remove backup cron job
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ k3s_backups_namespace }}"
    kind: Job
    name: "manual-backup"

- name: Remove manual backup job
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ k3s_backups_namespace }}"
    kind: CronJob
    name: "backup"
