---
- name: Namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
- block:
  - name: '"persistent" StorageClass (basic localpath for persistent volumes)'
    kubernetes.core.k8s:
      state: present
      template: 'persistent-storage-class.yaml'
  - name: "Storage"
    kubernetes.core.k8s:
      state: "{{ state }}"
      template: "storage.yaml"
  - name: "Deployment"
    kubernetes.core.k8s:
      state: "{{ state }}"
      template: "deployment.yaml"
  - name: "Service"
    kubernetes.core.k8s:
      state: "{{ state }}"
      template: "service.yaml"
  - name: "Ingress"
    kubernetes.core.k8s:
      state: "{{ state }}"
      template: "ingress.yaml"
  module_defaults:
    kubernetes.core.k8s:
      namespace: "{{ namespace }}"
      apply: true
