---
- name: "Create or update resources"
  when: k3s_service_action == 'create'
  ansible.builtin.include_tasks: ./update.yml
  vars:
    resources_state: present

- name: "Delete resources"
  when: k3s_service_action == 'delete'
  ansible.builtin.include_tasks: ./update.yml
  vars:
    resources_state: absent

- name: "Restart"
  when: k3s_service_action == 'restart'
  ansible.builtin.include_tasks: ./restart.yml

- name: "Wipe everything in namespace"
  when: k3s_service_action == 'wipe'
  ansible.builtin.include_tasks: ./wipe.yml
