- name: Setup one volume
  block:
    - name: "Ensure local storage directory exists"
      when: volume.type == 'local_path'
      ansible.builtin.file:
        path: "{{ home_dir }}/k3s/volumes/{{ k3s_service_name }}/{{ volume.name }}"
        state: directory
        mode: "0744"

    - name: "Setup volume: {{ volume.type }}"
      kubernetes.core.k8s:
        state: "{{ k3s_service_state }}"
        template: "storage/{{ volume.type }}.yaml.j2"
