- name: Setup one volume
  block:
    - name: Setup local_path volume
      when: volume.type == 'local_path'
      block:
        - name: 'Ensure local storage directory exists'
          ansible.builtin.file:
            path: "{{ home_dir }}/k3s/volumes/{{ k3s_service_name }}/{{ volume.name }}"
            state: directory
            mode: '0744'
        - name: Local_path storage setup
          kubernetes.core.k8s:
            state: "{{ k3s_service_state }}"
            template: "storage/local_path.yaml.j2"
