---
- name: Set interface attributes
  community.general.xml:
    path: "{{ config_file_local_path }}"
    xpath: "/opnsense/interfaces/{{ interface.value.name }}/{{ attribute.key }}"
    value: "{{ attribute.value }}"
    pretty_print: true
  loop: "{{ interface.value.xml_config | dict2items }}"
  loop_control:
    loop_var: attribute
