version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16-alpine
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    restart: always
volumes:
  uptime-kuma-data:
    external: true
