- name: Setup AdGuard Home (DNS for LAN + filters for WAN)
  hosts: adguardservs
  tasks:
    - include_tasks: "tasks/install-docker.yaml"
    - name: Copy systemd-resolved conf file over (turning off TCP 53 listen to free it for AdGuard)
      become: yes
      ansible.builtin.copy:
        src: "./resources/adguard/systemd-resolved.conf"
        dest: "/etc/systemd/resolved.conf"
      register: systemd_resolved_conf
    - name: Restart systemd-resolved
      become: yes
      ansible.builtin.systemd:
        name: "systemd-resolved"
        enabled: true
        state: restarted
      when: systemd_resolved_conf.changed
    - name: Ensure work and conf folders exist
      become: yes
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
        - "{{ home_dir }}/work"
        - "{{ home_dir }}/conf"
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ ansible_files_root }}/adguard"
        state: directory
        mode: '0755'
        recurse: yes
    - block:
      - name: Interpret docker compose template 
        template:
          src: ./resources/adguard/compose.yaml.j2
          dest: "{{ ansible_files_root }}/adguard/compose.yaml"
      - name: Interpret AdGuard configuration file
        become: yes
        template:
          src: ./resources/adguard/config.yaml.j2
          dest: "{{ home_dir }}/conf/AdGuardHome.yaml"
          backup: true
      notify: 
        - Run AdGuard-Home
  handlers:
    - name: Run AdGuard-Home
      become: yes
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_files_root }}/adguard"
        recreate: always # so that changes in config are applied
      
