---
- name: Setup AdGuard Home (DNS for LAN + filters for WAN)
  hosts: adguardservs
  tasks:
    - name: Ensure docker is installed
      ansible.builtin.include_tasks: "tasks/install-docker.yaml"
    - name: Copy systemd-resolved conf file over (turning off TCP 53 listen to free it for AdGuard)
      become: true
      ansible.builtin.copy:
        src: "./resources/adguard/systemd-resolved.conf"
        dest: "/etc/systemd/resolved.conf"
        mode: "0644"
      notify: Restart systemd-resolved
    - name: Restart systemd-resolved immediately if needed to free the TCP port
      ansible.builtin.meta: flush_handlers
    - name: Ensure work and conf folders exist
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        recurse: true
      loop:
        - "{{ home_dir }}/work"
        - "{{ home_dir }}/conf"
    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ ansible_files_root }}/adguard"
        state: directory
        mode: "0755"
        recurse: true
    - name: Copy files
      notify:
        - Run AdGuard-Home
      block:
        - name: Interpret docker compose template
          ansible.builtin.template:
            src: ./resources/adguard/compose.yaml.j2
            dest: "{{ ansible_files_root }}/adguard/compose.yaml"
            mode: "0644"
        - name: Interpret AdGuard configuration file
          become: true
          ansible.builtin.template:
            src: ./resources/adguard/config.yaml.j2
            dest: "{{ home_dir }}/conf/AdGuardHome.yaml"
            mode: "0644"
            backup: true
  handlers:
    - name: Restart systemd-resolved
      become: true
      ansible.builtin.systemd:
        name: "systemd-resolved"
        enabled: true
        state: restarted
    - name: Run AdGuard-Home
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_files_root }}/adguard"
        recreate: always # so that changes in config are applied
