---
- name: Setup backups
  hosts: backupservs
  roles:
    - role: backups
      vars:
        backups_snapshots:
          - default_cron:
              hour: 6
              minute: 0
            zfs_pool: nfs_pool
            filesystems:
              - name: home-assistant
              - name: websites
            archiving:
              target_dir: /srv/nfs/backups/k3s-volumes
              subdir_per_filesystem: false
              cron:
                # day: 1
                hour: 6
                minute: 30
        backups_rclone_conf_template_path: ./resources/backups/rclone.conf
        backups_rclone:
          - cron:
              hour: 7
              minute: 0
            src: /srv/nfs/backups
            target: "proton:/backups/homeserver-staging"

        backups_cleanup:
          - cron:
              hour: 7
              minute: 30
            dir: /srv/nfs/backups
            # Can also add  "regex" here, it defaults to '.*\.tar\.gz'
            older_than_days: 7
        snapshots_cleanup:
          - cron:
              hour: 7
              minute: 30
            # Can also add  "regex" here, it defaults to '.*'
            older_than_days: 31
