---
- name: Setup backups
  hosts: backupservs
  roles:
    - role: backups
      vars:
        backups_snapshots:
          - default_cron:
              hour: 6
              minute: 0
            zfs_pool: nfs_pool
            filesystems:
              - name: home-assistant
