- name: Install gateway
  hosts: cocobotservs
  tasks:
    - include_tasks: "tasks/install-docker.yaml"
    - name: Ensure directories for cocobot exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ansible_files_root }}/cocobot"
        - "{{ home_dir }}/cocobot"
    - name: Interpret cocobot conf template
      template:
        src: ./resources/cocobot/compose.yaml.j2
        dest: "{{ ansible_files_root }}/cocobot/compose.yaml"
      notify:
        - Run cocobot
  handlers:
    - name: Run cocobot
      become: yes
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_files_root }}/cocobot"
      
