- name: Setup duckdns
  hosts: duckdnsservs
  tasks:
    - name: Copy duckdns files
      copy:
        src: "./resources/duckdns"
        dest: "{{ home_dir }}"
    - name: Make duckdns script executable
      file:
        path: "{{ home_dir }}/duckdns/duck.sh"
        mode: u+x 
    - name: Setup duckdns cron job
      ansible.builtin.cron:
        name: "duckdns"
        minute: "*/5"
        job: "{{ home_dir }}/duckdns/duck.sh {{ duckdns_token }} >~/duck.lastrun.log 2>&1"
          
