- name: Deploy homepage
  hosts: mainhost
  roles:
    - homelab-app
  pre_tasks:
  post_tasks:
    - name: "render {{ item }} template"
      become: true
      ansible.builtin.template:
        src: "resources/homepage/{{ item }}.j2"
        dest: "{{ homelab_app_target_root_dir }}/config/{{ item }}"
        mode: "0644"
      loop:
        - settings.yaml
        - services.yaml
        - widgets.yaml
        - bookmarks.yaml
        - custom.css
        - custom.js
      notify: Restart homepage
  vars:
    homelab_app_name: homepage
    homelab_app_traefik_network: traefik
    homelab_app_apps_domain: "{{ homeserver_domain }}"
    homelab_app_internal_port: 3000
    homelab_app_compose_template: "resources/homepage/compose.yml.j2"
  handlers:
    - name: Restart homepage
      community.docker.docker_compose_v2:
        project_src: "{{ homelab_app_target_root_dir }}"
        state: restarted
