- name: "Deploy jellyfin"
  hosts: jellyfin
  roles:
    - homelab-app
  pre_tasks:
    - name: Install NTFS support
      become: true
      ansible.builtin.package:
        name: ntfs-3g

    - name: Create systemd mount unit for /mnt/media
      become: true
      ansible.builtin.template:
        src: ./resources/jellyfin/mnt-media.mount.j2
        dest: /etc/systemd/system/mnt-media.mount
        owner: root
        group: root
        mode: '0644'
    - name: Create systemd automount unit for /mnt/media
      become: true
      ansible.builtin.template:
        src: ./resources/jellyfin/mnt-media.automount.j2
        dest: /etc/systemd/system/mnt-media.automount
        owner: root
        group: root
        mode: '0644'
    - name: Reload systemd and enable/start automount
      become: true
      ansible.builtin.systemd:
        name: mnt-media.automount
        enabled: true
        state: started
        daemon_reload: true
    - name: Make sure the media Docker volume exists
      community.docker.docker_volume:
        name: "jellyfin-media"
        driver: local
        driver_options:
          type: none
          device: /mnt/media
          o: bind
  vars:
    homelab_app_name: jellyfin
    homelab_app_traefik_network: traefik
    homelab_app_apps_domain: "{{ homeserver_domain }}"
    homelab_app_internal_port: 8096
    homelab_app_compose_template: "resources/jellyfin/compose.yml.j2"
    homelab_app_volume_names:
      - config
      - cache
    homelab_app_backups:
      - volume: config
        cron: "0 6 * * *"
