---
- name: Setup k3s cluster (install k3s and helm on nodes)
  hosts: k3scontroller
  vars:
    k3s_release_version: v1.31.2+k3s1
    k3s_become: true
  tasks:
    - name: Python dependencies for kubernetes modules
      block:
        - name: Copy requirements.txt
          ansible.builtin.copy:
            src: "resources/k3s_setup/requirements.txt"
            dest: "/tmp/requirements.txt"
            mode: "0600"
        - name: Install requirements
          ansible.builtin.pip:
            requirements: /tmp/requirements.txt

    - name: Check if k3s is installed
      ansible.builtin.command: k3s --version
      register: k3s_installed
      ignore_errors: true
      failed_when: false
      changed_when: false
    - name: Setup k3s_server
      when: k3s_installed.rc != 0
      block:
        - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
          become: true
          ansible.builtin.shell: |
            swapoff -a
          changed_when: true
        - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
          become: true
          ansible.builtin.replace:
            path: /etc/fstab
            regexp: "^([^#].*?\\sswap\\s+sw\\s+.*)$"
            replace: "# \\1"
        - name: Install k3s
          ansible.builtin.include_role:
            name: xanmanning.k3s
          vars:
            k3s_release_version: v1.31.2+k3s1
            k3s_server:
              node-name: controller-vm
              node-label:
                - "high-io-storage=true"

              cluster-cidr: "{{ k3s_cluster_cidr }}"
              service-cidr: "{{ k3s_services_cidr }}"
              cluster-dns: "{{ k3s_cluster_dns }}"
    - name: Ensure kube folder exists
      ansible.builtin.file:
        path: "{{ home_dir }}/.kube"
        state: directory
        mode: "0744"
    - name: Copy k3s config for user
      become: true
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        remote_src: true
        dest: "{{ home_dir }}/.kube/config"
        owner: "{{ ansible_user }}"
        mode: "0600"
        force: false

    - name: Install helm
      ansible.builtin.include_role:
        name: geerlingguy.helm
      vars:
        helm_version: v3.16.3
        helm_platform: linux
        helm_arch: "{{ ansible_architecture_alt }}"

    - name: Setup NFS access
      block:
        - name: "Install nfs-common package"
          become: true
          ansible.builtin.package:
            name: nfs-common
        - name: "Create the nfs-subdir-external-provisioner namespace"
          kubernetes.core.k8s:
            kind: Namespace
            api_version: v1
            name: nfs-subdir-external-provisioner
        - name: "Add the nfs-subdir-external-provisioner helm repo"
          kubernetes.core.helm_repository:
            name: nfs-subdir-external-provisioner
            repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
        - name: "Install nfs-subdir-external-provisioner via helm"
          kubernetes.core.helm:
            name: nfs-subdir-external-provisioner
            chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
            chart_version: 4.0.18
            release_namespace: nfs-subdir-external-provisioner
            values:
              nfs:
                server: "{{ nfs_server }}"
                path: "{{ nfs_root_path }}"
              storageClass:
                archiveOnDelete: false # We want to reuse our data when redeploying the infra
                pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
