- name: "Deploy Navidrome (music streaming)"
  hosts: servarr
  roles:
    - homelab-app
  vars:
    homelab_app_name: navidrome
    homelab_app_cpu_shares: 2048
    homelab_app_traefik_network: traefik
    homelab_app_apps_domain: "{{ homeserver_domain }}"
    homelab_app_internal_port: 4533
    homelab_app_compose_template: "resources/navidrome/compose.yml.j2"
    homelab_app_volume_names:
      - data
    homelab_app_backups:
      - volume: data
        cron: "50 6 * * *"
