---
- name: Setup k3s cluster (install k3s and helm on nodes)
  hosts: nfsservs
  tasks:
    - name: Install nfs server
      ansible.builtin.include_role:
        name: "geerlingguy.nfs"
      vars:
        nfs_exports:
          - "/srv/nfs/k3s/volumes *(rw,sync,no_subtree_check)"
    - name: Setup permissions for exported directory
      ansible.builtin.file:
        dest: "/srv/nfs/k3s/volumes"
        owner: nobody # TODO improve security of this
        group: nogroup
        mode: "744"
        recurse: true
