---
- name: Setup NFS server
  hosts: nfsservs
  tasks:
    - name: Create nfs group
      become: true
      ansible.builtin.group:
        name: nfs
        gid: 4242
    - name: Create nfs user
      become: true
      ansible.builtin.user:
        name: nfs
        uid: 4242
        group: nfs

    - name: Install nfs server
      ansible.builtin.include_role:
        name: "geerlingguy.nfs"
      vars:
        nfs_exports:
          - "/srv/nfs/k3s/volumes {{ k3s_controller_ip }}(rw,sync,no_subtree_check)"
          - "/srv/nfs/backups/postgres {{ database_ip }}(rw,sync,no_subtree_check)"
    - name: Setup permissions for exported k3s volumes directory
      ansible.builtin.file:
        dest: "/srv/nfs/k3s/volumes"
        owner: nobody # TODO improve security of this
        group: nogroup
        mode: "744"
        recurse: true
    - name: Setup permissions for exported posgtres backups directory
      ansible.builtin.file:
        dest: "/srv/nfs/backups/postgres"
        owner: nfs
        group: nfs
        mode: "744"
        recurse: true
