---
- name: Setup NFS server
  become: true
  hosts: nfsservs
  vars:
    zfs_pool_name: "nfs_pool"
    nfs_server_exports:
      zfs:
        root: /srv/nfs/k3s/volumes
        subdirs:
          - name: home-assistant
            client: "{{ k3s_controller_ip }}"
          - name: websites
            client: "{{ k3s_controller_ip }}"
      basic:
        root: /srv/nfs/backups
        user: nfs
        group: nfs
        subdirs:
          - name: postgres
            client: "{{ database_ip }}"
  tasks:
    - name: Create nfs group
      become: true
      ansible.builtin.group:
        name: nfs
        gid: 4242
    - name: Create nfs user
      become: true
      ansible.builtin.user:
        name: nfs
        uid: 4242
        group: nfs

    - name: Install ZFS
      ansible.builtin.include_tasks:
        file: "tasks/install-zfs-{{ ansible_distribution }}.yaml"
      vars:
        disk_partition: /dev/sdb

    - name: Create a zfs file system for each zfs subdir
      community.general.zfs:
        name: "{{ zfs_pool_name }}/{{ item.name }}"
        state: present
        extra_zfs_properties:
          mountpoint: "{{ nfs_server_exports.zfs.root }}/{{ item.name }}"
      loop: "{{ nfs_server_exports.zfs.subdirs }}"

    - name: List nfs exports (basic)
      ansible.builtin.set_fact:
        database_nfs_exports: >
          {{
            (database_nfs_exports | default([])) + [
              nfs_server_exports.basic.root~'/'~item.name~' '~item.client~'(rw,sync,no_subtree_check)'
            ]
          }}
      loop: "{{ nfs_server_exports.basic.subdirs }}"
    - name: List nfs exports (ZFS)
      ansible.builtin.set_fact:
        k3s_nfs_exports: >
          {{
            (k3s_nfs_exports | default([])) + [
              nfs_server_exports.zfs.root~'/'~item.name~' '~item.client~'(rw,sync,no_subtree_check)'
            ]
          }}
      loop: "{{ nfs_server_exports.zfs.subdirs }}"
    - name: Install nfs server
      ansible.builtin.include_role:
        name: "geerlingguy.nfs"
      vars:
        nfs_exports: "{{ database_nfs_exports + k3s_nfs_exports }}"

    - name: Setup permissions for exported nfs directories (ZFS)
      ansible.builtin.file:
        dest: "{{ nfs_server_exports.zfs.root }}/{{ item.name }}"
        owner: "{{ nfs_server_exports.zfs.user | default(ansible_user) }}"
        group: "{{ nfs_server_exports.zfs.group | default(ansible_user) }}"
        mode: "777" # TODO not ideal, fix nfs permissions
        state: directory
        recurse: true
      loop: "{{ nfs_server_exports.zfs.subdirs }}"
    - name: Setup permissions for exported nfs directories (basic)
      ansible.builtin.file:
        dest: "{{ nfs_server_exports.basic.root }}/{{ item.name }}"
        owner: "{{ nfs_server_exports.basic.user | default(ansible_user) }}"
        group: "{{ nfs_server_exports.basic.group | default(ansible_user) }}"
        mode: "777" # TODO not ideal, fix nfs permissions
        state: directory
        recurse: true
      loop: "{{ nfs_server_exports.basic.subdirs }}"
