---
- name: Mount NFS folder
  hosts: nfsclients

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.package:
        name:
          - nfs-common

    - name: Create nfs group
      become: true
      ansible.builtin.group:
        name: nfs
        gid: 4242
    - name: Create nfs user
      become: true
      ansible.builtin.user:
        name: nfs
        uid: 4242
        group: nfs

    - name: Mount dirs
      with_items: "{{ nfs_dirs }}"
      ansible.builtin.include_tasks: tasks/mount-nfs-dir.yaml
