---
- name: Install and setup PostgreSQL
  hosts: postgresservs
  become: true
  # become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  roles:
    - role: postgres
      vars:
        postgres_host_ip: "{{ ansible_host }}"
        postgres_client_cidr: "{{ k3s_controller_ip }}/32"
        postgres_lan_cidr: "{{ lan_cidr }}"
