- name: "Deploy radarr"
  hosts: servarr
  roles:
    - homelab-app
  vars:
    homelab_app_name: radarr
    homelab_app_cpu_shares: 512
    homelab_app_traefik_network: traefik
    homelab_app_apps_domain: "{{ homeserver_domain }}"
    homelab_app_internal_port: 7878
    homelab_app_compose_template: "resources/radarr/compose.yml.j2"
    homelab_app_volume_names:
      - config
    homelab_app_backups:
      - volume: config
        cron: "55 6 * * *"
  pre_tasks:
    - name: Servarr stack setup
      ansible.builtin.import_tasks: tasks/servarr-setup.yaml
