- name: "Restore an app data using restic"
  hosts: mainhost
  # gather_facts: false
  tasks:
    - name: "Run restore task from homelab-app role"
      include_role:
        name: homelab-app
        tasks_from: restic_restore_app
      vars:
        homelab_app_name: jellyfin
        # restore_volume: config  # optional; omit to restore all
