---
- name: "Restore all servar stack data"
  hosts: mainhost
  tasks:
    - name: "Restore {{ app }}"
      ansible.builtin.include_tasks: ./tasks/restore-app.yaml
      vars:
        homelab_app_name: "{{ app }}"
      loop:
        - radarr
        - sonarr
        - lidarr
        - prowlarr
        - qbitorrent
      loop_control:
        loop_var: app
