---
- name: Install a k3s service
  hosts: homeassistantservs
  tasks:
    - name: Deploy the test k3s service
      ansible.builtin.include_role:
        name: "k3s_service"
      vars:
        k3s_service_namespace: home-assistant
        k3s_service_name: assistant
        k3s_service_image: "ghcr.io/home-assistant/home-assistant:2024.10"
        k3s_service_container_port: 8123
        k3s_service_data_volume_mount_path: /config
        k3s_service_data_volumes:
          - type: nfs
            name: all-data
            mount_path: /config
            size: 1Gi
        k3s_service_config_files:
          - template: "./resources/home-assistant/initial-configuration.yaml.j2"
            dest: "/config/configuration.yaml"
          - template: "./resources/home-assistant/empty-template.yaml.j2"
            dest: "/config/automations.yaml"
            init_only: true
          - template: "./resources/home-assistant/empty-template.yaml.j2"
            dest: "/config/scripts.yaml"
            init_only: true
          - template: "./resources/home-assistant/empty-template.yaml.j2"
            dest: "/config/scenes.yaml"
            init_only: true
