- name: Deploy docker app with patching
  hosts: uptime-kuma
  vars:
    app_name: uptime-kuma
    app_internal_port: 3001
    app_path: "./resources/{{ app_name }}"
    app_target_root_dir: "{{ apps_root }}/{{ app_name }}"
    compose_template: "{{ app_path }}/compose.yml.j2"
    patch_template: "{{ app_path }}/patch.yml.j2"
    rendered_compose: "/tmp/base-compose.yml"
    rendered_patch: "/tmp/patch.yml"

  tasks:
    - name: Ensure app config dir exists
      file:
        path: "{{ app_target_root_dir }}"
        state: directory
        mode: "0744"

    - name: Render base compose template
      delegate_to: localhost
      template:
        src: "{{ compose_template }}"
        dest: "{{ rendered_compose }}"

    - name: Render patch template
      delegate_to: localhost
      template:
        src: "{{ patch_template }}"
        dest: "{{ rendered_patch }}"

    - name: Load rendered compose
      delegate_to: localhost
      slurp:
        src: "{{ rendered_compose }}"
      register: base_compose_raw

    - name: Load rendered patch
      delegate_to: localhost
      slurp:
        src: "{{ rendered_patch }}"
      register: patch_raw

    - name: Parse YAMLs
      set_fact:
        base_compose: "{{ base_compose_raw.content | b64decode | from_yaml }}"
        patch_data: "{{ patch_raw.content | b64decode | from_yaml }}"

    - name: Deep merge base and patch
      set_fact:
        final_compose: >-
          {{
            base_compose | combine(patch_data, recursive=True, list_merge='append_rp')
          }}

    - name: Save merged compose file
      copy:
        dest: "{{ app_target_root_dir }}/compose.yml"
        content: "{{ final_compose | to_nice_yaml(indent=2) }}"
        owner: "{{ ansible_user }}"
        mode: "0644"

    - name: Make sure the data volume exists
      community.docker.docker_volume:
        name: "{{ app_name }}-data"

    - name: Bring up the app with compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_target_root_dir }}"
        state: present
