- name: Deploy docker app with patching
  hosts: uptime-kuma
  vars:
    app_name: uptime-kuma
    app_path: "./resources/{{ app_name }}"
    app_target_root_dir: "{{ apps_root }}/{{ app_name }}"
  tasks:
    - name: Ensure app config dir exists
      file:
        path: "{{ app_target_root_dir }}"
        state: directory
        mode: "0744"
    - name: Load base compose
      delegate_to: localhost
      slurp:
        src: "{{ app_path }}/compose.yml"
      register: base_compose_raw

    - name: Load patch
      delegate_to: localhost
      slurp:
        src: "{{ app_path }}/patch.yml"
      register: patch_raw

    - name: Parse YAMLs
      set_fact:
        base_compose: "{{ base_compose_raw.content | b64decode | from_yaml }}"
        patch_data: "{{ patch_raw.content | b64decode | from_yaml }}"

    - name: Deep merge base and patch
      set_fact:
        final_compose: >-
          {{
            base_compose | combine(patch_data, recursive=True, list_merge='append_rp')
          }}

    - name: Save merged compose file
      copy:
        dest: "{{ app_target_root_dir }}/compose.yml"
        content: "{{ final_compose | to_nice_yaml(indent=2) }}"
        owner: "{{ ansible_user }}"
        mode: "0644"

    - name: Make sure the data volume exists
      community.docker.docker_volume:
        name: "{{ app_name }}-data"

    - name: Bring up the app with compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_target_root_dir }}"
        state: present
