---
- name: Install uptime-kuma
  hosts: k3scontroller
  tasks:
    - name: Deploy the k3s service
      ansible.builtin.include_role:
        name: "k3s_service"
      vars:
        k3s_service_namespace: uptime-kuma
        k3s_service_name: uptime
        k3s_service_image: "louislam/uptime-kuma:1.23.16-alpine"
        k3s_service_container_port: 3001
        k3s_service_data_volumes:
          - type: longhorn-simple
            name: app-data
            mount_path: /app/data
            size: 2Gi
        k3s_service_backups: "{{ default_k3s_backup_config }}"