---
services:
  gateway:
    container_name: gateway
    labels:
      - homeserver.container-category=service
    build: ./
    image: services-gateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    environment:
      TZ: "France/Paris"
    networks:
      - public-net
      - services-net
      - monitoring-net
networks:
  public-net:
    external: true
  services-net:
    external: true
  monitoring-net:
    external: true
