ansible_host: 10.142.1.2
ansible_user: adguard_user
home_dir: /home/{{ hostvars.dnshost.ansible_user }}
ansible_files_root: /home/{{ hostvars.dnshost.ansible_user }}/ansible-files
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no" #Staging VM, host might change (be recreated) quite often
