---
ansible_host: 10.142.10.10
ansible_user: k3s_user
home_dir: /home/{{ hostvars.k3scontroller.ansible_user }}
ansible_files_root: /home/{{ hostvars.k3scontroller.ansible_user }}/ansible-files
ansible_python_interpreter: /home/{{ hostvars.k3scontroller.ansible_user }}/k3s/venv/bin/python
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
