# TODO add ansible playbook configure the default staging route on proxmox
# ip route replace 10.142.0.0/16 dev vmbr1001 via 10.142.1.1
# Then call the ansible playbooks from Terraform

- name: Setup Opnsense firewall
  hosts: opnsenseservs
  connection: local # Run from the control node (=this machine)
  gather_facts: no # No point in gathering facts on the local machine
  vars:
    lan_interface_device: "vtnet2"
    lan_interface_id: "opt1"
    legacyvlan_interface_id: "opt2"
    config_file_local_path: /tmp/{{ inventory_hostname }}.config.xml
    piserv_ip: "192.168.50.2"
    legacy_vm_ip: "10.142.200.10"
  module_defaults:
    group/ansibleguy.opnsense.all:
      ssl_verify: false
      firewall: "{{ ansible_host }}"
      api_key: "{{ opnsense_api_key }}"
      api_secret: "{{ opnsense_api_secret }}"
  tasks:
    - name: opnsense role
      include_role:
        name: "../roles/opnsense"
