# TODO add ansible playbook configure the default staging route on proxmox
# ip route replace 10.142.0.0/16 dev vmbr1001 via 10.142.1.1
# Then call the ansible playbooks from Terraform

- name: Setup Opnsense firewall
  hosts: opnsenseservs
  connection: local # Run from the control node (=this machine)
  gather_facts: no # No point in gathering facts on the local machine
  vars:
    lan_interface_device: "vtnet2"
    lan_interface_id: "opt1"
    legacyvlan_interface_id: "opt2"
    config_file_local_path: /tmp/{{ inventory_hostname }}.config.xml
    piserv_ip: "192.168.50.2"
    legacy_vm_ip: "10.142.200.10"
  module_defaults:
    group/ansibleguy.opnsense.all:
      ssl_verify: false
      firewall: "{{ ansible_host }}"
      api_key: "{{ opnsense_api_key }}"
      api_secret: "{{ opnsense_api_secret }}"
  tasks:
    - name: Create legacy VLAN
      ansibleguy.opnsense.interface_vlan:
        description: "Legacy network, with all containers deployed on the same host"
        interface: "{{ lan_interface_device }}"
        vlan: 200
    # interfaces assignment
    - name: Import interfaces config file from host
      connection: ssh
      ansible.builtin.fetch:
        src: /conf/config.xml
        dest: "{{ config_file_local_path }}"
        flat: yes
      vars:
        ansible_python_interpreter: /usr/local/bin/python3
    # TODO turn into a role with proper defaults etc
    - include_tasks: tasks/setup-firewall-interface.yaml
      loop: "{{ interfaces | dict2items }}"
      loop_control:
        loop_var: interface
    # TODO make backup conf file
    - name: Update interfaces config file
      connection: ssh
      become: yes
      copy:
        src: "{{ config_file_local_path }}"
        dest: /conf/config.xml
      vars:
        ansible_python_interpreter: /usr/local/bin/python3
      register: ifconfig
      # Test if really needed
    - name: Reboot to parse new config
      ansibleguy.opnsense.system:
        action: reboot
      when: ifconfig.changed
    
    - name: opnsense role
      include_role:
        name: "../roles/opnsense"
