- name: Install Zigbee2MQTT
  hosts: zigbee2mqttservs
  tasks:
    - include_tasks: "tasks/install-docker.yaml"
    - name: Make sure the docker network exists
      become: yes
      community.docker.docker_network:
        name: "services-net"
    - name: Make sure the mqtt volume exists
      become: yes
      community.docker.docker_volume:
        name: mosquitto-data
      register: volume
    - name: Check if the Zigbee2MQTT volume exists
      become: yes
      docker_volume_info:
        name: zigbee2mqtt-data
      register: volume
    - name: Create the volume if needed
      become: yes
      community.docker.docker_volume:
        name: zigbee2mqtt-data
    - name: Ensure Zigbee2MQTT config folder exists
      ansible.builtin.file:
        path: "{{ ansible_files_root }}/zigbee2mqtt"
        state: directory
        mode: '0755'
        recurse: yes
    - name: Interpret Zigbee2MQTT docker compose template 
      template:
        src: ./resources/zigbee2mqtt/compose.yaml.j2
        dest: "{{ ansible_files_root }}/zigbee2mqtt/compose.yaml"
      notify: 
        - Run Zigbee2MQTT 

    # Initialise the configuration file only when the volume is new
    - block:
      - name: Interpret Zigbee2MQTT initial configuration template
        template:
          src: ./resources/zigbee2mqtt/initial-configuration.yaml.j2
          dest: "{{ ansible_files_root }}/zigbee2mqtt/initial-configuration.yaml"
      - name: Use ephemeral container to mount the volume
        become: yes
        docker_container:
          name: initialise-zigbee2mqtt-config
          labels:
            homeserver.container-category: ephemeral
          image: alpine # A tiny container that stays up and do nothing
          state: started
          recreate: yes
          tty: true # So that it stays up
          volumes:
            - zigbee2mqtt-data:/data
      - name: Copy the initial configuration file to the volume
        become: yes
        community.docker.docker_container_copy_into:
          container: initialise-zigbee2mqtt-config
          path: "{{ ansible_files_root }}/zigbee2mqtt/initial-configuration.yaml"
          container_path: /data/configuration.yaml
      - name: stop and remove the ephemeral container
        become: yes
        docker_container:
          name: initialise-zigbee2mqtt-config
          state: absent
      when: not volume.exists
      notify:
        - Run Zigbee2MQTT

  handlers:
    - name: Run Zigbee2MQTT
      become: yes
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_files_root }}/zigbee2mqtt"
        recreate: always # so that changes in config are applied
      
