---
- name: Validate and initialise variables
  tags: always
  ansible.builtin.include_tasks: init_vars.yml
- name: Install dependencies
  tags: always
  ansible.builtin.include_tasks: install_dependencies.yml
- name: Setup local backups
  tags: always
  ansible.builtin.include_tasks: setup_local_backups.yml
- name: Restore from backups
  tags: restore
  ansible.builtin.import_tasks: restore.yml
