---
- name: Validate and initialise variables
  tags: always
  ansible.builtin.include_tasks: init_vars.yml
- name: Install dependencies
  tags: always
  ansible.builtin.include_tasks: install_dependencies.yml
- name: Setup backups
  tags: always
  ansible.builtin.include_tasks: setup_backups.yml
- name: Restore from backups
  tags: never,restore-local
  ansible.builtin.import_tasks: restore_local.yml
- name: Restore from snapshots
  tags: never,restore-snapshot
  ansible.builtin.import_tasks: restore_snapshot.yml
