---
- name: Count the backup files before
  become: true
  tags: always
  register: before
  changed_when: false
  ansible.builtin.shell:
    cmd: "set -o pipefail && find {{ item.src }} -type f | wc -l"
    executable: /bin/bash
- name: Pull all latest backups from rclone
  tags: always
  changed_when: false
  ansible.builtin.command:
    cmd: "pull-latest-rclone-files{{ item.name }}"
  register: rclone_pull
- name: Rclone pull output
  tags: always
  ansible.builtin.debug:
    msg: "{{ rclone_pull.stdout_lines }}"
- name: Count the backup files after
  become: true
  tags: always
  register: after
  changed_when: after.stdout != before.stdout
  ansible.builtin.shell:
    cmd: "set -o pipefail && find {{ item.src }} -type f | wc -l"
    executable: /bin/bash
