---
- name: Verify input vars
  tags: restore
  when: backups_restore_directory_regex is undefined
  ansible.builtin.fail:
    msg: "You must define the backups_restore_directory_regex variable"

- name: Set restore facts
  ansible.builtin.set_fact:
    restore_version: "{{ backups_restore_version | default(backups_default_restore_version) }}"

- name: Get ZFS mount points
  become: true
  loop: "{{ _zfs_snapshots }}"
  when: item.archiving
  register: zfs_mounts
  changed_when: false
  ansible.builtin.command:
    cmd: "zfs get -H -o value mountpoint {{ item.pool }}/{{ item.filesystem }}"

- name: Build archive restore data from zfs snapshots config
  loop: "{{ _zfs_snapshots }}"
  when: item.archiving
  ansible.builtin.set_fact:
    _zfs_archives: >-
      {{ (_zfs_archives | default([])) + [
      {
        'name': item.name,
        'zfs_path':  item.pool + '/' + item.filesystem,
        'target': (
          item.archiving.target_dir if not item.archiving.subdir_per_filesystem 
          else item.archiving.target_dir + '/' + item.filesystem
        ),
         'src': (zfs_mounts.results | selectattr('item.name', 'eq', item.name) | map(attribute='stdout') | first),
      }
      ] }}

- name: Display archives to restore
  ansible.builtin.debug:
    var: _zfs_archives

- name: Restore all matching snapshot archives
  loop: "{{ _zfs_archives }}"
  ansible.builtin.include_tasks: restore_single_archive.yml
