---
- name: Verify input vars
  when: backups_restore_snapshot_regex is undefined
  ansible.builtin.fail:
    msg: "You must define the backups_restore_snapshot_regex variable"
- name: Set restore facts
  ansible.builtin.set_fact:
    restore_version: "{{ backups_restore_version | default(backups_default_restore_version) }}"

- name: Restore all matching snapshots
  loop: "{{ _zfs_snapshots }}"
  ansible.builtin.include_tasks: restore_single_snapshot.yml
